drop table order_elems;
drop table orders;
drop table adress;
drop table adress;
--создание таблиц
create table customers(
email nvarchar2(50),password nvarchar2(50) Encrypt not null, 
CONSTRAINT user_pk PRIMARY KEY (email)
); 

--дом текстовый ввиду наличия корпусов, индексов букв и т.д

create table adress(
adress_id int GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1, email nvarchar2(50), city nvarchar2(30) Encrypt not null,street nvarchar2(30) Encrypt not null,
house nvarchar2(30) Encrypt not null,a_floor int Encrypt not null,appartment int Encrypt not null,
CONSTRAINT adress_pk PRIMARY KEY (adress_id),
CONSTRAINT adr_mail_fk foreign key(email)references customers(email)
); 




create table orders(order_id int GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
email nvarchar2(50),adress_id int, 
 ord_date date Encrypt,
CONSTRAINT order_pk PRIMARY KEY (order_id),
CONSTRAINT ord_mail_fk foreign key(email)references customers(email),
CONSTRAINT adress_fk foreign key(adress_id)references adress(adress_id),
ord_status smallint
); 

CREATE TABLE Order_elems (
  order_id INT,
  part_id INT,
  count INT,
  FOREIGN KEY (order_id) REFERENCES Orders(order_id) ON DELETE CASCADE,
  FOREIGN KEY (part_id) REFERENCES Parts(part_id)
);


create table parts(
part_id int GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
p_model nvarchar2(50),
manufacturer nvarchar2(50),
price number(16,2)
,p_count int,p_description nvarchar2(160),
type nvarchar2(15),p_status smallint default 0,
CONSTRAINT part_pk PRIMARY KEY (part_id)
); 

CREATE TABLE CPU (
  part_id INT, FOREIGN KEY (part_id) REFERENCES Parts(part_id),
  freq INT,
  cores SMALLINT,
  arch NVARCHAR2(50),
  socket NVARCHAR2(20)
);
CREATE TABLE GPU (
  part_id INT, FOREIGN KEY (part_id) REFERENCES Parts(part_id),
  memtype NVARCHAR2(10),
  memory INT,
  gpu_chip NVARCHAR2(50)
);

CREATE TABLE RAM (
  part_id INT, FOREIGN KEY (part_id) REFERENCES Parts(part_id),
  memtype NVARCHAR2(10),
  memory INT,
  freq INT
);

CREATE TABLE Storage (
  part_id INT, FOREIGN KEY (part_id) REFERENCES Parts(part_id),
  interface NVARCHAR2(10),
  memory INT,
  memtype NVARCHAR2(10)
);

CREATE TABLE Mboard (
  part_id INT, FOREIGN KEY (part_id) REFERENCES Parts(part_id),
  socket NVARCHAR2(20),
  chipset NVARCHAR2(50),
  memtype NVARCHAR2(10)
);

select * from user_procedures;
